### ISSUE TITLE
Heavy symetrical top test

### ISSUE THREAD

**Issue by nicolasmecamas** [parmes/solfec#65]
[heavy-symmetrical-top_DEF.py.docx](https://github.com/tkoziara/solfec/files/958564/heavy-symmetrical-top_DEF.py.docx)
Hi Tomek,
I am working on the test "Heavy symetrical top". It well run for RIGID behavior. But when I use deformable behavior, It generates the following error:
Could you please explain me?
Thank you in advance,
Nicolas

Traceback (most recent call last):
 File "<string>", line 1, in <module>
 File "heavy-symmetrical-top_DEF.​py",​ line 1113, in <module>
 bod.conf = expmap((0.05, 0, 0)) + (0, 0, 0)
ValueError: 'conf' must have 513 elements

**Comment by tkoziara** [comment]
You see; this is because this is a specifically rigid-body oriented example, where only integration of the rotational motion is looked at; In this case body configuration (bod.conf in the code) is made of 12 components: a 3x3 rotation matrix (stored column-wise in a vector) followed by a 3-component current position of the mass centre;

Producing a deformable version of this test will require care; I am assuming that you already have a FE mesh of the top that produces diagonal inertia tensor equal to [5, 5, 1]; bod.conf now is the configuration of the FE mesh -- the displacement vectors; it has as many elements as there are nodes * 3; this seems to be 513 in your case; here, instead of using bod.con = exmap(...) + (...) type initialisation (which works for rigid bodies only), you can use the [ROTATE](http://parmes.org/solfec/user/utilities.html?highlight=rotate#rotate) routine to apply the initial rotation;

further, the `torque` routine will not make sense in the FE case; you will still need to use the force callback, but redefine the `torque` routine so that applies an equivalent torque as a set of point forces applied to all mesh nodes;

keep me posted about how you are getting on:)

**Comment by nicolasmecamas** [comment]
[heavy-symmetrical-top_DEF.py.docx](https://github.com/tkoziara/solfec/files/958567/heavy-symmetrical-top_DEF.py.docx)
I forgot upload the python file :)

**Comment by nicolasmecamas** [comment]
It has not yet worked. I am trying to debug and I keep you informed.

**Comment by tkoziara** [comment]
I can comment that this example is not trivial to convert into an FE case; you will not be able to directly plot angular velocity components (there are none); this will need to be recovered from linear velocities of mesh nodes; but once set up it may help to verify the accuracy of the integration of rotational motion in the finite element case fore stiff bodies, where comparison with the rigid case makes sense;

**Comment by nicolasmecamas** [comment]
Hi tomek,
I am still blocked with this castest. 
I think about a solution to impose the rotation at node. We can create the linear velocity at node that varies as function of time. 
But I dont know how to create a velocity field at node that varies versus time?
Do you have an idea? Do you think it is easy to update the source file this posibility?
Thank you in advance,
Nicolas

**Comment by tkoziara** [comment]
To set time-dependent velocity at node you can use [SET_VELOCITY](http://parmes.org/solfec/user/constraints.html#set-velocity) in combination with [TIME_SERIES](http://parmes.org/solfec/user/times.html);

What are you trying to test - actually - by attempting this entire conversion? Perhaps there is a simpler - FE specific - test out there that we could try to find and adapt.

**Comment by nicolasmecamas** [comment]
Hi Tomek,
I attempted it but I see the following problem. Could you please take a look on the attached file?
Thank you in advance,
Nicolas
________________________
Peter@linux:​/Works/Objet_FEM_rot$​ solfec heavy-symmetrical-top_DEF.py
------------------------------​------------------------------​----------------------------
INITIALLY DOFS 513, BODIES: 1 (OBS: 0, RIG: 0, PRB: 0, FEM: 1)
------------------------------​------------------------------​----------------------------
TIME: 0 ... DOMAIN ... (STEP: 0.001) ValueError: Tuple of invalid size was returned from FORCE callback


[heavy-symmetrical-top_DEF.py.docx](https://github.com/tkoziara/solfec/files/1058561/heavy-symmetrical-top_DEF.py.docx)

**Comment by tkoziara** [comment]
Nicolas,
You are working with a finite element body: the applied force needs to have as many components as there are degrees of freedom; the returned tuple has to have the same size as the input displacements 'q' and velocities 'u'; and also note that `torque` as such does not make sense for finite elements - you will need to apply equivalent force couples; If you wish to apply just one force coupe at two nodes - then simply make all other components zero; The format of the force vector is very simple: (fx1, fy1, fz1, fx2, fy2, fz2, ..., fxN, fyN, fzN), where N is the number of mesh nodes;
I hope that helps:)
Tomek

**Comment by tkoziara** [comment]
@nicolasmecamas I am closing this issue for now, assuming outdated; feel free to reopen if needed.
